import { PrismaClient } from "@prisma/client";import bcrypt from "bcryptjs";
const db=new PrismaClient();
const images={challenge:"",summer:"",focus:""};
async function main(){
  const leadership=await db.programCategory.upsert({where:{slug:"leadership"},update:{},create:{name:"القيادة وتطوير الذات",slug:"leadership"}});const skills=await db.programCategory.upsert({where:{slug:"skills"},update:{},create:{name:"المهارات والحياة",slug:"skills"}});
  const programs=[{title:"صيفك تحدي وتغيير",slug:"summer-challenge",shortDescription:"رحلة صيفية مليئة بالتحديات العملية التي تصنع عادات إيجابية وثقة مستدامة.",description:"برنامج تفاعلي يجمع بين ورش تطوير الذات والتحديات الجماعية والأنشطة الحركية. تتعلم المشاركات تحديد أهدافهن وبناء العادات وإدارة الوقت، ضمن بيئة داعمة بإشراف مدربات متخصصات.",coverImage:images.challenge,cardImage:images.challenge,location:"مقر نادي طاقات - الرياض",startDate:new Date("2026-09-05"),endDate:new Date("2026-09-19"),registrationDeadline:new Date("2026-09-03"),capacity:30,price:0,status:"PUBLISHED" as const,featured:true,showInSlider:true,isNew:true,categoryId:leadership.id},{title:"صيف طاقات 2",slug:"taqat-summer-2",shortDescription:"تجربة صيفية متجددة تجمع التعلم بالمرح وتنمّي مهارات التواصل والعمل الجماعي.",description:"النسخة الثانية من برنامج صيف طاقات، وفيها مسارات إبداعية وجلسات إرشاد ومشروعات جماعية قصيرة. صمم البرنامج ليمنح الفتيات مساحة آمنة للتجربة والتعبير وبناء صداقات إيجابية.",coverImage:images.summer,cardImage:images.summer,location:"مركز طاقات المجتمعي",startDate:new Date("2026-10-01"),endDate:new Date("2026-10-15"),registrationDeadline:new Date("2026-09-27"),capacity:40,price:150,status:"PUBLISHED" as const,featured:true,showInSlider:true,isNew:false,categoryId:skills.id},{title:"نادي ركيز",slug:"rakeez-club",shortDescription:"لقاءات أسبوعية تعزز التركيز والاتزان والوعي بالذات بأساليب عملية وممتعة.",description:"مجتمع أسبوعي مستمر يقدم تمارين تركيز ووعي، وحوارات موجهة، وأدوات عملية للتعامل مع الضغوط الدراسية والحياتية. تُبنى اللقاءات تدريجيًا لتناسب مختلف المستويات.",coverImage:images.focus,cardImage:images.focus,location:"عن بُعد",startDate:new Date("2026-11-02"),endDate:new Date("2026-12-21"),registrationDeadline:new Date("2026-10-30"),capacity:25,price:0,status:"PUBLISHED" as const,featured:false,showInSlider:true,isNew:true,categoryId:skills.id}];
  for(const p of programs)await db.program.upsert({where:{slug:p.slug},update:p,create:p});
  const partnerData=[["مؤسسة إثراء",""],["مبادرة نمو",""],["مجتمع أثر",""],["شركة آفاق",""]];for(let i=0;i<partnerData.length;i++){const[name,logo]=partnerData[i];const existing=await db.partner.findFirst({where:{name}});if(existing)await db.partner.update({where:{id:existing.id},data:{logo,displayOrder:i+1,active:true}});else await db.partner.create({data:{name,logo,displayOrder:i+1}})}
  if(await db.testimonial.count()===0)await db.testimonial.createMany({data:[{quote:"وجدت في طاقات مساحة تشجعني على المحاولة دون خوف، وتعلمت كيف أحول فكرتي إلى خطوات واضحة.",name:"سارة العتيبي",title:"مشاركة في برنامج صيفك",rating:5,displayOrder:1},{quote:"التفاصيل الصغيرة في البرامج تصنع فرقًا كبيرًا، من جودة المدربات إلى روح المجتمع الداعمة.",name:"نورة القحطاني",title:"ولية أمر",rating:5,displayOrder:2},{quote:"خرجت بصديقات جدد ومهارات أستخدمها كل يوم. تجربة تستحق أن تتكرر.",name:"لينا الشهري",title:"عضوة نادي ركيز",rating:5,displayOrder:3}]});
  if(await db.staffMember.count()===0)await db.staffMember.createMany({data:[{name:"أمل السبيعي",jobTitle:"المديرة التنفيذية",image:"",bio:"تقود رؤية النادي وشراكاته وبرامجه النوعية.",displayOrder:1},{name:"ريم الحربي",jobTitle:"مديرة البرامج",image:"",bio:"تصمم تجارب تعلم تراعي احتياجات الفتيات وطموحاتهن.",displayOrder:2},{name:"هناء الدوسري",jobTitle:"مسؤولة المجتمع",image:"",bio:"تبني جسور التواصل وترافق المشاركات في رحلتهن.",displayOrder:3}]});
  if(await db.statistic.count()===0)await db.statistic.createMany({data:[{title:"المستفيدات",value:300,prefix:"+",displayOrder:1},{title:"شراكات فاعلة",value:15,prefix:"+",displayOrder:2},{title:"برنامجًا نوعيًا",value:50,prefix:"+",displayOrder:3},{title:"رضا المشاركات",value:96,suffix:"%",displayOrder:4}]});
  await db.aboutContent.upsert({where:{id:"main"},update:{},create:{id:"main",introduction:"نادي طاقات للفتيات مبادرة مجتمعية تصنع بيئة آمنة ومحفزة لاكتشاف القدرات وتنمية المهارات وبناء العلاقات الإيجابية.",vision:"أن نكون الوجهة الأولى لتمكين الفتيات وصناعة جيل واثق ومبادر وفاعل في مجتمعه.",mission:"تقديم برامج وتجارب نوعية تجمع المعرفة بالتطبيق، يقودها مختصون وتدعمها شراكات مؤثرة.",goals:"تنمية المهارات الشخصية والقيادية، تعزيز الوعي والاتزان، توسيع فرص التعلم والتطوع، وبناء مجتمع مستدام من الفتيات الملهمات.",values:"التمكين، الأمان، الإبداع، المسؤولية، التعاون، والأثر."}});
  const settings={clubName:"نادي طاقات للفتيات",email:"hello@taqat.sa",phone:"011 000 0000",mobile:"050 000 0000",address:"الرياض، المملكة العربية السعودية",footerDescription:"مساحة ملهمة تمكّن الفتيات وتنمّي طاقاتهن عبر برامج نوعية ومجتمع داعم.",copyright:"جميع الحقوق محفوظة لنادي طاقات للفتيات",instagram:"https://instagram.com",x:"https://x.com",whatsapp:"https://wa.me/966500000000",siteTitle:"نادي طاقات للفتيات | نُلهم طاقتك",metaDescription:"مساحة آمنة وملهمة تقدم برامج نوعية لتمكين الفتيات وتنمية مهاراتهن."};for(const[key,value]of Object.entries(settings))await db.siteSetting.upsert({where:{key},update:{value},create:{key,value}});
  const email=process.env.SEED_ADMIN_EMAIL,password=process.env.SEED_ADMIN_PASSWORD;if(email&&password){if(password.length<8)throw new Error("SEED_ADMIN_PASSWORD must have at least 8 characters");await db.user.upsert({where:{email},update:{role:"ADMIN",active:true},create:{name:"مديرة النظام",email,phone:"0500000000",passwordHash:await bcrypt.hash(password,12),role:"ADMIN"}})}else process.stdout.write("Admin seed skipped: set SEED_ADMIN_EMAIL and SEED_ADMIN_PASSWORD.\n");
}
main().finally(()=>db.$disconnect());
