"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { db } from "@/lib/db"; import { requireAdmin } from "@/lib/auth"; import { slugify } from "@/lib/utils";
const text=(fd:FormData,key:string)=>String(fd.get(key)||"").trim();const bool=(fd:FormData,key:string)=>fd.get(key)==="on";const num=(fd:FormData,key:string)=>Number(fd.get(key)||0);
export async function saveSettingsAction(formData:FormData){await requireAdmin();const keys=["clubName","email","phone","mobile","address","footerDescription","copyright","instagram","x","whatsapp","siteTitle","metaDescription","logo","defaultSocialImage"];await db.$transaction(keys.map(key=>db.siteSetting.upsert({where:{key},create:{key,value:text(formData,key)},update:{value:text(formData,key)}})));revalidatePath("/", "layout");redirect("/admin/settings?saved=1")}
export async function saveHomepageAction(formData:FormData){await requireAdmin();const textKeys=["programsHeading","partnersHeading","statisticsHeading","testimonialsHeading"],boolKeys=["showPrograms","showPartners","showStatistics","showTestimonials"];await db.$transaction([...textKeys.map(key=>db.siteSetting.upsert({where:{key},create:{key,value:text(formData,key),group:"home"},update:{value:text(formData,key)}})),...boolKeys.map(key=>db.siteSetting.upsert({where:{key},create:{key,value:String(bool(formData,key)),group:"home"},update:{value:String(bool(formData,key))}}))]);revalidatePath("/");redirect("/admin/homepage?saved=1")}
export async function saveAboutAction(formData:FormData){await requireAdmin();await db.aboutContent.upsert({where:{id:"main"},create:{id:"main",introduction:text(formData,"introduction"),vision:text(formData,"vision"),mission:text(formData,"mission"),goals:text(formData,"goals"),values:text(formData,"values")},update:{introduction:text(formData,"introduction"),vision:text(formData,"vision"),mission:text(formData,"mission"),goals:text(formData,"goals"),values:text(formData,"values")}});revalidatePath("/about");redirect("/admin/about?saved=1")}
export async function saveProgramAction(id:string|undefined,formData:FormData){await requireAdmin();const data={title:text(formData,"title"),slug:slugify(text(formData,"slug")||text(formData,"title")),shortDescription:text(formData,"shortDescription"),description:text(formData,"description"),coverImage:text(formData,"coverImage"),cardImage:text(formData,"cardImage")||text(formData,"coverImage"),location:text(formData,"location"),startDate:new Date(text(formData,"startDate")),endDate:new Date(text(formData,"endDate")),registrationDeadline:new Date(text(formData,"registrationDeadline")),capacity:num(formData,"capacity"),price:num(formData,"price"),status:text(formData,"status") as "DRAFT"|"PUBLISHED"|"ARCHIVED",featured:bool(formData,"featured"),showInSlider:bool(formData,"showInSlider"),isNew:bool(formData,"isNew"),categoryId:text(formData,"categoryId")||null};if(!data.title||!data.slug||!data.description||data.capacity<1)throw new Error("بيانات البرنامج الأساسية غير مكتملة");if(id)await db.program.update({where:{id},data});else await db.program.create({data});revalidatePath("/programs");revalidatePath("/");redirect("/admin/programs?saved=1")}
export async function archiveProgramAction(id:string){await requireAdmin();await db.program.update({where:{id},data:{status:"ARCHIVED"}});revalidatePath("/programs");revalidatePath("/admin/programs")}
export async function savePartnerAction(formData:FormData){await requireAdmin();const id=text(formData,"id"),data={name:text(formData,"name"),logo:text(formData,"logo"),url:text(formData,"url")||null,displayOrder:num(formData,"displayOrder"),active:bool(formData,"active")};if(id)await db.partner.update({where:{id},data});else await db.partner.create({data});revalidatePath("/");revalidatePath("/admin/partners")}
export async function deletePartnerAction(id:string){await requireAdmin();await db.partner.delete({where:{id}});revalidatePath("/");revalidatePath("/admin/partners")}
export async function saveStatisticAction(formData:FormData){await requireAdmin();const id=text(formData,"id"),data={title:text(formData,"title"),value:num(formData,"value"),prefix:text(formData,"prefix")||null,suffix:text(formData,"suffix")||null,icon:text(formData,"icon")||null,displayOrder:num(formData,"displayOrder"),active:bool(formData,"active")};if(id)await db.statistic.update({where:{id},data});else await db.statistic.create({data});revalidatePath("/");revalidatePath("/admin/statistics")}
export async function deleteStatisticAction(id:string){await requireAdmin();await db.statistic.delete({where:{id}});revalidatePath("/");revalidatePath("/admin/statistics")}
export async function saveTestimonialAction(formData:FormData){await requireAdmin();const id=text(formData,"id"),data={quote:text(formData,"quote"),name:text(formData,"name"),title:text(formData,"title")||null,rating:Math.min(5,Math.max(1,num(formData,"rating"))),displayOrder:num(formData,"displayOrder"),active:bool(formData,"active")};if(id)await db.testimonial.update({where:{id},data});else await db.testimonial.create({data});revalidatePath("/");revalidatePath("/admin/testimonials")}
export async function deleteTestimonialAction(id:string){await requireAdmin();await db.testimonial.delete({where:{id}});revalidatePath("/");revalidatePath("/admin/testimonials")}
export async function saveStaffAction(formData:FormData){await requireAdmin();const id=text(formData,"id"),data={name:text(formData,"name"),jobTitle:text(formData,"jobTitle"),image:text(formData,"image"),bio:text(formData,"bio")||null,contactUrl:text(formData,"contactUrl")||null,displayOrder:num(formData,"displayOrder"),active:bool(formData,"active")};if(id)await db.staffMember.update({where:{id},data});else await db.staffMember.create({data});revalidatePath("/staff");revalidatePath("/admin/staff")}
export async function deleteStaffAction(id:string){await requireAdmin();await db.staffMember.delete({where:{id}});revalidatePath("/staff");revalidatePath("/admin/staff")}
export async function moderateCommentAction(id:string,status:"APPROVED"|"HIDDEN"|"DELETE"){await requireAdmin();if(status==="DELETE")await db.programComment.delete({where:{id}});else await db.programComment.update({where:{id},data:{status}});revalidatePath("/admin/comments")}
export async function updateUserAction(id:string,formData:FormData){const admin=await requireAdmin();if(id===admin.id&&text(formData,"role")!=="ADMIN")throw new Error("لا يمكنك إزالة صلاحية حسابك الإداري");await db.user.update({where:{id},data:{role:text(formData,"role") as "USER"|"ADMIN",active:bool(formData,"active")}});revalidatePath("/admin/users")}
export async function updateRegistrationAction(id:string,formData:FormData){await requireAdmin();await db.programRegistration.update({where:{id},data:{status:text(formData,"status") as "CONFIRMED"|"CANCELLED"|"WAITLIST"}});revalidatePath("/admin/registrations")}
